# Generated by Django 6.0.1 on 2026-01-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_jobs', models.IntegerField(default=2)),
                ('max_jobs', models.IntegerField(default=5)),
                ('max_time', models.IntegerField(default=120)),
            ],
        ),
    ]
