# Generated by Django 6.0.1 on 2026-01-21 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_latitude', models.FloatField()),
                ('customer_longitude', models.FloatField()),
                ('customer_address', models.TextField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OPTIMIZED', 'Optimized'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('company_id', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('min_job_threshold', models.PositiveIntegerField(default=1)),
                ('max_job_threshold', models.PositiveIntegerField(default=10)),
                ('min_time_threshold', models.PositiveIntegerField(help_text='in minutes')),
                ('max_time_threshold', models.PositiveIntegerField(help_text='in minutes')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminSettings',
        ),
        migrations.AddField(
            model_name='jobqueue',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='admin_app.salesperson'),
        ),
    ]
