# Generated by Django 6.0.1 on 2026-01-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_admin_jobqueue_salesperson_delete_adminsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='role',
            field=models.CharField(default='ADMIN', max_length=20),
        ),
    ]
