# Generated by Django 6.0.1 on 2026-01-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_salesperson_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='role',
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(default='ADMIN', max_length=20),
        ),
    ]
