# Generated by Django 6.0.1 on 2026-01-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_salesperson_role_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='role',
            field=models.CharField(default='SALESPERSON', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobqueue',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.salesperson'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='max_time_threshold',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='min_time_threshold',
            field=models.PositiveIntegerField(),
        ),
    ]
