# Generated by Django 6.0.1 on 2026-01-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_salesperson_role_alter_jobqueue_salesperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='max_time_threshold',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='min_time_threshold',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
