# Generated by Django 6.0.1 on 2026-02-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_salesperson_max_time_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
