# Generated by Django 6.0.1 on 2026-02-10 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_salesperson_latitude_salesperson_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='company_id',
        ),
    ]
