# Generated by Django 6.0.1 on 2026-04-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_remove_salesperson_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('FINANCE', 'Finance'), ('SALESPERSON', 'Salesperson')], default='FINANCE', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='jobqueue',
            name='priority_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FINANCE', 'Finance'), ('SALESPERSON', 'Salesperson')], default='ADMIN', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FINANCE', 'Finance'), ('SALESPERSON', 'Salesperson')], default='SALESPERSON', max_length=20),
        ),
    ]
