# Generated by Django 6.0.1 on 2026-04-04 04:50

import django.db.models.deletion
from django.db import migrations, models


def link_existing_jobs_to_customers(apps, schema_editor):
    JobQueue = apps.get_model('admin_app', 'JobQueue')
    Customer = apps.get_model('customer_app', 'Customer')

    for job in JobQueue.objects.filter(customer__isnull=True):
        customer = Customer.objects.filter(
            name=job.customer_name,
            address=job.customer_address,
            latitude=job.customer_latitude,
            longitude=job.customer_longitude,
        ).first()

        if customer:
            job.customer_id = customer.id
            job.save(update_fields=['customer'])


def unlink_existing_jobs_from_customers(apps, schema_editor):
    JobQueue = apps.get_model('admin_app', 'JobQueue')
    JobQueue.objects.update(customer=None)


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_finance_jobqueue_priority_order_alter_admin_role_and_more'),
        ('customer_app', '0004_customer_status_customer_visit_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobqueue',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer'),
        ),
        migrations.RunPython(link_existing_jobs_to_customers, unlink_existing_jobs_from_customers),
    ]
