# Generated by Django 6.0.1 on 2026-01-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('request_created_at', models.DateTimeField(auto_now_add=True)),
                ('is_assigned', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerApplication',
        ),
    ]
