# Generated by Django 6.0.1 on 2026-02-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_customer_delete_customerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='annual_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='loan_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('PERSONAL', 'Personal Loan'), ('HOME', 'Home Loan'), ('VEHICLE', 'Vehicle Loan'), ('BUSINESS', 'Business Loan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
