# Generated by Django 6.0.1 on 2026-04-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_customer_aadhar_number_customer_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='visit_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/'),
        ),
    ]
